version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - DB_CONNECTION_STRING=root:123456@tcp(mysql:3306)/socialDB?charset=utf8mb4&parseTime=true&loc=Local
      - REDIS_HOST=redis:6379

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: socialDB
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  mysql-data:
  redis-data:
